// ******************************************************************************************
// * This project is licensed under the GNU Affero GPL v3. Copyright © 2014 A3Wasteland.com *
// ******************************************************************************************
//	Lootspawner junction list for buildings to classes
//	Author: Na_Palm (BIS forums)
//-------------------------------------------------------------------------------------
//"Buildingstoloot_list" array of [buildingname, class]
//                              buildingname:   building class name (in editor debug console use "typeof BIS_fnc_camera_target"
//                                              to monitor and then copy/paste or any other method you know...)
//                              class:          0-civil, 1-military, ... (add more as you wish)
//
//!!!EVERY building must have only ONE entry here AND been in ONE class!!!
//-------------------------------------------------------------------------------------
Buildingstoloot_list = [];
/*[
	//["Land_Addon_01_V1_dam_F", 0],        //not viable
	//["Land_Airport_center_F", 0],         //no positions
	//["Land_cargo_addon01_V1_F", 0],       //no positions
	//["Land_cargo_addon01_V2_F", 0],       //no positions
	//["Land_cargo_addon02_V2_F", 0],       //no positions
	//["Land_Castle_01_tower_F", 0],        //no positions
	//["Land_Communication_anchor_F", 0],   //no positions
	//["Land_Communication_F", 0],          //no positions
	//["Land_dp_smallFactory_F", 0],        //no positions
	//["Land_dp_smallTank_F", 0],           //no positions
	//["Land_Factory_Hopper_F", 0],         //no positions
	//["Land_Garage_V1_dam_F", 0],          //not viable
	//["Land_ReservoirTank_Airport_F", 0],  //no positions
	//["Land_ReservoirTower_F", 2],         //no positions
	//["Land_Shed_Big_F", 0],               //no positions
	//["Land_Shed_Small_F", 0],             //no positions
	//["Land_TBox_F", 0],                   //no positions
	//["Land_TTowerBig_1_F", 2],            //no positions
	//["Land_TTowerBig_2_F", 2],            //no positions
	["Land_Airport_left_F", 0],
	["Land_Airport_right_F", 0],
	["Land_Airport_Tower_dam_F", 2],
	["Land_Airport_Tower_F", 2],
	["Land_cargo_house_slum_F", 0],
	["Land_Cargo_House_V1_F", 1],
	["Land_Cargo_House_V2_F", 1],
	["Land_Cargo_House_V3_F", 1],
	["Land_Cargo_HQ_V1_F", 1],
	["Land_Cargo_HQ_V2_F", 1],
	["Land_Cargo_HQ_V3_F", 1],
	["Land_Cargo_Patrol_V1_F", 1],
	["Land_Cargo_Patrol_V2_F", 1],
	["Land_Cargo_Patrol_V3_F", 1],
	["Land_Cargo_Tower_V1_F", 1],
	["Land_Cargo_Tower_V3_F", 1],
	["Land_CarService_F", 2],
	["Land_Chapel_Small_V1_F", 0],
	["Land_Chapel_Small_V2_F", 0],
	["Land_Chapel_V1_F", 0],
	["Land_Chapel_V2_F", 0],
	["Land_Crane_F", 0],
	["Land_dp_bigTank_F", 2],
	["Land_dp_mainFactory_F", 2],
	["Land_d_Stone_Shed_V1_F", 0],
	["Land_d_Windmill01_F", 0],
	["Land_FuelStation_Build_F", 0],
	["Land_FuelStation_Shed_F", 0],
	["Land_Hangar_F", 2],
	["Land_Hospital_main_F", 0],
	["Land_Hospital_side1_F", 0],
	["Land_Hospital_side2_F", 0],
	["Land_i_Addon_02_V1_F", 0],
	["Land_i_Addon_03mid_V1_F", 0],
	["Land_i_Addon_03_V1_F", 0],
	["Land_i_Addon_04_V1_F", 0],
	["Land_i_Barracks_V1_F", 2],
	["Land_i_Barracks_V2_F", 1],
	["Land_i_Garage_V1_F", 0],
	["Land_i_Garage_V2_F", 0],
	["Land_i_House_Big_01_V1_dam_F", 0],
	["Land_i_House_Big_01_V1_F", 0],
	["Land_i_House_Big_01_V2_F", 0],
	["Land_i_House_Big_01_V3_F", 0],
	["Land_i_House_Big_02_V1_dam_F", 0],
	["Land_i_House_Big_02_V1_F", 0],
	["Land_i_House_Big_02_V2_F", 0],
	["Land_i_House_Big_02_V3_F", 0],
	["Land_i_House_Small_01_V1_dam_F", 0],
	["Land_i_House_Small_01_V1_F", 0],
	["Land_i_House_Small_01_V2_dam_F", 0],
	["Land_i_House_Small_01_V2_F", 0],
	["Land_i_House_Small_01_V3_F", 0],
	["Land_i_House_Small_02_V1_dam_F", 0],
	["Land_i_House_Small_02_V1_F", 0],
	["Land_i_House_Small_02_V2_F", 0],
	["Land_i_House_Small_02_V3_F", 0],
	["Land_i_House_Small_03_V1_dam_F", 0],
	["Land_i_House_Small_03_V1_F", 0],
	["Land_i_Shed_Ind_F", 2],
	["Land_i_Shop_01_V1_dam_F", 0],
	["Land_i_Shop_01_V1_F", 0],
	["Land_i_Shop_01_V2_F", 0],
	["Land_i_Shop_01_V3_F", 0],
	["Land_i_Shop_02_V1_dam_F", 0],
	["Land_i_Shop_02_V1_F", 0],
	["Land_i_Shop_02_V2_F", 0],
	["Land_i_Shop_02_V3_F", 0],
	["Land_i_Stone_HouseBig_V1_dam_F", 0],
	["Land_i_Stone_HouseBig_V1_F", 0],
	["Land_i_Stone_HouseBig_V2_F", 0],
	["Land_i_Stone_HouseBig_V3_F", 0],
	["Land_i_Stone_HouseSmall_V1_dam_F", 0],
	["Land_i_Stone_HouseSmall_V1_F", 0],
	["Land_i_Stone_HouseSmall_V2_F", 0],
	["Land_i_Stone_HouseSmall_V3_F", 0],
	["Land_i_Stone_Shed_V1_dam_F", 0],
	["Land_i_Stone_Shed_V1_F", 0],
	["Land_i_Stone_Shed_V2_F", 0],
	["Land_i_Stone_Shed_V3_F", 0],
	["Land_i_Windmill01_F", 0],
	["Land_LightHouse_F", 0],
	["Land_Lighthouse_small_F", 0],
	["Land_Metal_Shed_F", 2],
	["Land_MilOffices_V1_F", 1],
	["Land_Offices_01_V1_F", 0],
	["Land_Radar_F", 2],
	["Land_Research_house_V1_F", 3],
	["Land_Research_HQ_F", 3],
	["Land_Slum_House01_F", 0],
	["Land_Slum_House02_F", 0],
	["Land_Slum_House03_F", 0],
	["Land_spp_Tower_F", 2],
	["Land_Unfinished_Building_01_F", 2],
	["Land_Unfinished_Building_02_F", 2],
	["Land_u_Addon_01_V1_F", 0],
	["Land_u_Addon_02_V1_F", 0],
	["Land_u_Barracks_V2_F", 1],
	["Land_u_House_Big_01_V1_F", 0],
	["Land_u_House_Big_02_V1_F", 0],
	["Land_u_House_Small_01_V1_dam_F", 0],
	["Land_u_House_Small_01_V1_F", 0],
	["Land_u_House_Small_02_V1_dam_F", 0],
	["Land_u_House_Small_02_V1_F", 0],
	["Land_u_Shed_Ind_F", 2],
	["Land_u_Shop_01_V1_F", 0],
	["Land_u_Shop_02_V1_F", 0],
	["Land_u_Barracks_V2_F", 1],
	["Land_Shed_W02_EP1", 1],
	["Land_Shed_M01_ruins_EP1", 1],
	["Land_Shed_W03_ruins_EP1", 1],
	["Land_Shed_M03_ruins_EP1", 1],
	["Land_Com_tower_ep1", 1],
	["Land_Com_tower_ruins_EP1", 1],
	["Land_House_L_1_EP1", 1],
	["Land_House_L_3_EP1", 1],
	["Land_House_L_3_dam_EP1", 1],
	["Land_House_L_4_EP1", 1],
	["Land_House_L_4_dam_EP1", 1],
	["Land_House_L_6_EP1", 1],
	["Land_House_L_7_EP1", 1],
	["Land_House_L_7_dam_EP1", 1],
	["Land_House_L_8_EP1", 1],
	["Land_House_L_8_dam_EP1", 1],
	["Land_House_L_9_EP1", 1],
	["Land_House_L_1_ruins_EP1", 1],
	["Land_House_L_3_ruins_EP1", 1],
	["Land_House_L_4_ruins_EP1", 1],
	["Land_House_L_6_ruins_EP1", 1],
	["Land_House_L_7_ruins_EP1", 1],
	["Land_House_L_8_ruins_EP1", 1],
	["Land_House_L_9_ruins_EP1", 1],
	["Land_House_K_1_EP1", 1],
	["Land_House_K_3_EP1", 1],
	["Land_House_K_3_dam_EP1", 1],
	["Land_House_K_5_EP1", 1],
	["Land_House_K_5_dam_EP1", 1],
	["Land_House_K_6_EP1", 1],
	["Land_House_K_6_dam_EP1", 1],
	["Land_House_K_7_EP1", 1],
	["Land_House_K_7_dam_EP1", 1],
	["Land_House_K_8_EP1", 1],
	["Land_House_K_8_dam_EP1", 1],
	["Land_Terrace_K_1_EP1", 1],
	["Land_House_K_1_ruins_EP1", 1],
	["Land_House_K_5_ruins_EP1", 1],
	["Land_House_K_3_ruins_EP1", 1],
	["Land_House_K_6_ruins_EP1", 1],
	["Land_House_K_7_ruins_EP1", 1],
	["Land_House_K_8_ruins_EP1", 1],
	["Land_House_C_1_EP1", 1],
	["Land_House_C_1_dam_EP1", 1],
	["Land_House_C_1_v2_EP1", 1],
	["Land_House_C_1_v2_dam_EP1", 1],
	["Land_House_C_2_EP1", 1],
	["Land_House_C_2_DAM_EP1", 1],
	["Land_House_C_3_EP1", 1],
	["Land_House_C_3_dam_EP1", 1],
	["Land_House_C_4_EP1", 1],
	["Land_House_C_4_dam_EP1", 1],
	["Land_House_C_5_EP1", 1],
	["Land_House_C_5_dam_EP1", 1],
	["Land_House_C_5_V1_EP1", 1],
	["Land_House_C_5_V1_dam_EP1", 1],
	["Land_House_C_5_V2_EP1", 1],
	["Land_House_C_5_V2_dam_EP1", 1],
	["Land_House_C_5_V3_EP1", 1],
	["Land_House_C_5_V3_dam_EP1", 1],
	["Land_House_C_9_EP1", 1],
	["Land_House_C_9_dam_EP1", 1],
	["Land_House_C_10_EP1", 1],
	["Land_House_C_10_dam_EP1", 1],
	["Land_House_C_11_EP1", 1],
	["Land_House_C_11_dam_EP1", 1],
	["Land_House_C_12_EP1", 1],
	["Land_House_C_12_dam_EP1", 1],
	["Land_House_C_1_ruins_EP1", 1],
	["Land_House_C_1_v2_ruins_EP1", 1],
	["Land_House_C_2_ruins_EP1", 1],
	["Land_House_C_3_ruins_EP1", 1],
	["Land_House_C_4_ruins_EP1", 1],
	["Land_House_C_5_ruins_EP1", 1],
	["Land_House_C_6_ruins_EP1", 1],
	["Land_House_C_7_ruins_EP1", 1],
	["Land_House_C_8_ruins_EP1", 1],
	["Land_House_C_9_ruins_EP1", 1],
	["Land_House_C_10_ruins_EP1", 1],
	["Land_House_C_11_ruins_EP1", 1],
	["Land_House_C_12_ruins_EP1", 1],
	["A_Villa", 1],
	["Land_A_Villa_EP1", 1],
	["Land_A_Villa_dam_EP1", 1],
	["Land_A_Villa_ruins_EP1", 1],
	["A_Stationhouse", 1],
	["Land_A_Stationhouse_ep1", 1],
	["Land_a_stationhouse_ruins_ep1", 1],
	["A_Office01", 1],
	["Land_A_Office01_EP1", 1],
	["Land_A_Office01_ruins_ep1", 1],
	["A_Mosque_small", 1],
	["Land_A_Mosque_small_1_EP1", 1],
	["Land_A_Mosque_small_1_dam_EP1", 1],
	["Land_A_Mosque_small_2_EP1", 1],
	["Land_A_Mosque_small_2_dam_EP1", 1],
	["Land_A_Mosque_small_1_ruins_EP1", 1],
	["Land_A_Mosque_small_2_ruins_EP1", 1],
	["A_Mosque_big", 1],
	["Land_A_Mosque_big_hq_EP1", 1],
	["Land_A_Mosque_big_minaret_1_EP1", 1],
	["Land_A_Mosque_big_minaret_1_dam_EP1", 1],
	["Land_A_Mosque_big_minaret_2_EP1", 1],
	["Land_A_Mosque_big_minaret_2_dam_EP1", 1],
	["Land_A_Mosque_big_wall_EP1", 1],
	["Land_A_Mosque_big_wall_corner_EP1", 1],
	["Land_A_Mosque_big_wall_gate_EP1", 1],
	["Land_A_Mosque_big_wall_gate_dam_EP1", 1],
	["Land_A_Mosque_big_hq_ruins_EP1", 1],
	["Land_A_Mosque_big_addon_ruins_EP1", 1],
	["Land_A_Mosque_big_minaret_1_ruins_EP1", 1],
	["Land_A_Mosque_big_minaret_2_ruins_EP1", 1],
	["Land_A_Mosque_big_wall_gate_ruins_EP1", 1],
	["Land_A_Mosque_big_wall_corner_ruins_EP1", 1],
	["Land_A_Mosque_big_wall_ruins_EP1", 1],
	["A_minaret_Porto", 1],
	["Land_A_Minaret_Porto_EP1", 1],
	["Land_A_Minaret_Porto_ruins_EP1", 1],
	["Land_A_Minaret_EP1", 1],
	["Land_A_Minaret_dam_EP1", 1],
	["Land_A_Minaret_ruins_EP1", 1],
	["Land_A_CityGate1_EP1", 1],
	["Land_A_CityGate1_ruins_EP1", 1],
	["Land_A_BuildingWIP_EP1", 1],
	["Land_A_BuildingWIP_ruins_EP1", 1],
	["Ind_Colatn_Mine", 1],
	["Land_Ind_Coltan_Conv1_10_EP1", 1],
	["Land_Ind_Coltan_Conv1_Main_EP1", 1],
	["Land_Ind_Coltan_Conv1_end_EP1", 1],
	["Land_Ind_Coltan_Conv2_EP1", 1],
	["Land_Ind_Coltan_Hopper_EP1", 1],
	["Land_Ind_Coltan_Main_EP1", 1],
	["Land_Misc_Coltan_Heap_EP1", 1],
	["Land_Ind_Coltan_Conv1_10_ruins_EP1", 1],
	["Land_Ind_Coltan_Conv1_Main_ruins_EP1", 1],
	["Land_Ind_Coltan_Conv2_ruins_EP1", 1],
	["Land_Ind_Coltan_Hopper_ruins_EP1", 1],
	["Land_Ind_Coltan_Main_ruins_EP1", 1],
	["Ind_FuelStation", 1],
	["Land_Ind_FuelStation_Feed_EP1", 1],
	["Land_Ind_FuelStation_Build_EP1", 1],
	["Land_Ind_FuelStation_Shed_EP1", 1],
	["Land_Ind_FuelStation_Build_ruins_EP1", 1],
	["Land_Ind_FuelStation_Shed_ruins_EP1", 1],
	["Land_Ind_Garage01_EP1", 1],
	["Ind_Oil_Mine", 1],
	["Land_Ind_Oil_Pump_EP1", 1],
	["Land_Ind_Oil_Tower_EP1", 1],
	["Land_Ind_Oil_Tower_ruins_EP1", 1],
	["Land_Ind_Oil_Pump_ruins_EP1", 1],
	["Ind_pipes", 1],
	["Land_IndPipe1_stair_EP1", 1],
	["Land_IndPipe2_big_18ladder_EP1", 1],
	["Land_IndPipe2_bigL_R_EP1", 1],
	["Land_IndPipe2_bigL_L_EP1", 1],
	["Land_IndPipe2_bigBuild1_R_EP1", 1],
	["Land_IndPipe2_bigBuild1_L_EP1", 1],
	["Land_IndPipe2_bigBuild2_L_EP1", 1],
	["Land_IndPipe2_bigBuild2_R_EP1", 1],
	["Land_IndPipe2_big_ground1_EP1", 1],
	["Land_IndPipe2_big_ground2_EP1", 1],
	["Ind_PowerStation", 1],
	["Land_Ind_PowerStation_EP1", 1],
	["Land_Ind_PowerStation_ruins_EP1", 1],
	["Ind_Shed", 1],
	["Land_Ind_Shed_01_EP1", 1],
	["Land_Ind_Shed_02_EP1", 1],
	["Land_Ind_Shed_01_ruins_EP1", 1],
	["Land_Ind_Shed_02_ruins_EP1", 1],
	["Wall", 1],
	["Wall_L", 1],
	["Land_Wall_L_2m5_gate_EP1", 1],
	["Land_Wall_L1_gate_EP1", 1],
	["Land_Wall_L3_gate_EP1", 1],
	["Land_Wall_L3_5m_EP1", 1],
	["Land_Wall_L3_pillar_EP1", 1],
	["Land_Wall_L3_5m_ruins_EP1", 1],
	["Land_Wall_L3_pillar_ruins_EP1", 1],
	["Land_Wall_L_Mosque_1_EP1", 1],
	["Land_Wall_L_Mosque_2_EP1", 1],
	["Land_Wall_L_Mosque_1_ruins_EP1", 1],
	["Land_Wall_L_Mosque_2_ruins_EP1", 1],
	["Wall_FenW2_6_EP1", 1],
	["Wall_L_2m5_EP1", 1],
	["Wall_L1_2m5_EP1", 1],
	["Wall_L1_5m_EP1", 1],
	["Wall_L2_5m_EP1", 1],
	["Wall_L3_5m_EP1", 1],
	["Mil", 1],
	["Land_Mil_ControlTower_EP1", 1],
	["Land_Mil_ControlTower_dam_EP1", 1],
	["Land_Mil_ControlTower_ruins_EP1", 1],
	["Land_Mil_House_EP1", 1],
	["Land_Mil_House_dam_EP1", 1],
	["Land_Mil_House_ruins_EP1", 1],
	["Land_Mil_Barracks_i_EP1", 1],
	["Land_Mil_Barracks_i_ruins_EP1", 1],
	["Land_Mil_Barracks_EP1", 1],
	["Land_Mil_Barracks_Ruins_EP1", 1],
	["Land_Mil_Barracks_L_EP1", 1],
	["Land_Mil_Barracks_L_ruins_EP1", 1],
	["Land_Mil_Guardhouse_EP1", 1],
	["Land_Mil_Guardhouse_ruins_EP1", 1],
	["Land_Mil_hangar_EP1", 1],
	["Land_Mil_hangar_ruins_EP1", 1],
	["Land_Mil_Repair_center_EP1", 1],
	["Land_Mil_Repair_center_ruins_EP1", 1],
	["Land_u_Barracks_V2_F", 1],
	["Land_Shed_03_F", 1],
	["Land_Slum_01_F", 1],
	["Land_House_Small_03_F", 1],
	["Land_House_Native_02_F", 1],
	["Land_Slum_02_F", 1],
	["Land_House_Native_01_F", 1],
	["Land_Shed_05_F", 1],
	["Land_House_Small_06_F", 1],
	["Land_House_Big_01_F", 1],
	["Land_House_Small_02_F", 1],
	["Land_House_Small_05_F", 1],
	["Land_House_Small_01_F", 1],
	["Land_Shed_02_F", 1],
	["Land_House_Small_04_F", 1],
	["Land_Slum_03_F", 1],
	["Land_GarageShelter_01_F", 1],
	["Land_i_Shed_Ind_F", 1],
	["Land_Hotel_02_F", 1],
	["Land_House_Big_03_F", 1],
	["Land_Addon_04_F", 1],
	["Land_Shop_City_07_F", 1],
	["Land_Shop_Town_01_F", 1],
	["Land_Shop_City_04_F", 1],
	["Land_Supermarket_01_F", 1],
	["Land_Shop_Town_03_F", 1],
	["Land_Shop_Town_02_F", 1],
	["Land_PierWooden_02_16m_F", 1],
	["Land_PierWooden_02_ladder_F", 1],
	["Land_PierWooden_02_hut_F", 1],
	["Land_PierWooden_02_30deg_F", 1],
	["Land_Temple_Native_01_F", 1],
	["Land_School_01_F", 1],
	["Land_Shop_Town_05_F", 1],
	["Land_FuelStation_02_workshop_F", 1],
	["Land_FireEscape_01_short_F", 1],
	["Land_Shop_City_01_F", 1],
	["Land_Shop_City_06_F", 1],
	["Land_Shop_City_02_F", 1],
	["Land_Hotel_01_F", 1],
	["Land_House_Big_04_F", 1],
	["Land_Warehouse_03_F", 1],
	["Land_FuelStation_01_workshop_F", 1],
	["Land_FuelStation_01_shop_F", 1],
	["Land_Mausoleum_01_F", 1],
	["Land_Barracks_01_grey_F", 1],
	["Land_Airport_01_controlTower_F", 1],
	["Land_Airport_01_terminal_F", 1],
	["Land_Barracks_01_camo_F", 1],
	["Land_MilOffices_V1_F", 1],
	["Land_Hangar_F", 1],
	["Land_House_Big_02_F", 1],
	["Land_PierWooden_02_barrel_F", 1],
	["Land_PierWooden_01_dock_F", 1],
	["Land_PierWooden_01_hut_F", 1],
	["Land_PierWooden_01_16m_F", 1],
	["Land_PierWooden_01_10m_noRails_F", 1],
	["Land_u_Shed_Ind_F", 1],
	["Land_Track_01_bridge_F", 1],
	["Land_ContainerLine_01_F", 1],
	["Land_dp_bigTank_F", 1],
	["Land_FireEscape_01_tall_F", 1],
	["Land_StorageTank_01_small_F", 1],
	["Land_ContainerLine_02_F", 1],
	["Land_Offices_01_V1_F", 1],
	["Land_ContainerLine_03_F", 1],
	["Land_MobileCrane_01_F", 1],
	["Land_MobileCrane_01_hook_F", 1],
	["Land_MultistoryBuilding_01_F", 1],
	["Land_Shop_City_05_F", 1],
	["Land_MultistoryBuilding_03_F", 1],
	["Land_MultistoryBuilding_04_F", 1],
	["Land_Airport_01_hangar_F", 1],
	["Land_PierWooden_01_platform_F", 1],
	["Land_Airport_02_hangar_left_F", 1],
	["Land_Airport_02_hangar_right_F", 1],
	["Land_Airport_02_terminal_F", 1],
	["Land_Airport_02_controlTower_F", 1],
	["Land_DPP_01_mainFactory_F", 1],
	["Land_SCF_01_washer_F", 1],
	["Land_SCF_01_feeder_F", 1],
	["Land_SCF_01_heap_bagasse_F", 1],
	["Land_SCF_01_boilerBuilding_F", 1],
	["Land_SCF_01_chimney_F", 1],
	["Land_Radar_F", 1],
	["Land_SM_01_shed_unfinished_F", 1],
	["Land_ContainerCrane_01_F", 1],
	["Land_SM_01_shed_F", 1],
	["Land_Crane_F", 1],
	["Land_Pier_F", 1]
];*/




//-------------------------------------------------------------------------------------
//function only runs once on beginning of mission, not really needs a compile
//fill Buildingstoloot_list with buildingnames only

_configs = "true" configClasses (missionconfigFile >> "CfgBuildingPos");

{
	Buildingstoloot_list pushBack (configName _x);
	//diag_log format["-- LOOTSPAWNER DEBUG add to Buildingstoloot_list: %1 ", (configName _x)];
} forEach _configs;
